// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajukbtwyhwyajmjinfai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqdWtidHd5aHd5YWptamluZmFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc2NDM3NzEsImV4cCI6MjA1MzIxOTc3MX0.4tUYSXTpX18kh-FadRZkBGymOcxAIxdbENOgrNJKOmo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);